library(tufte)
library(rmarkdown)
library(tint)
render('lists_conversion_experience.rmd',output_format=tufte_handout())
#render('lists_conversion_experience.rmd',output_format=ioslides_presentation)
#render('lists_conversion_experience.rmd',output_format=tintPdf())
