library(rmarkdown)
library(bookdown)
library(tint)
library(tufte)
#render('lists_conversion_experience.rmd',output_format=tufte_handout())
#render('lists_conversion_experience.rmd',output_format=ioslides_presentation)
#render('lists_conversion_experience.rmd',output_format=tintPdf())
#render('lists_conversion_experience.rmd',output_format=word_document2())
#render('lists_conversion_experience.rmd',output_file='index.html', output_format=html_document2(toc=TRUE, toc_depth = 1, toc_float=TRUE, theme='journal'))
render('lists_conversion_experience.rmd',output_file='index.html', output_format=tufte_html2(toc=TRUE, toc_depth = 1))
